[tool.pytest.ini_options]

asyncio_mode = 'auto' 

addopts = '-v -s --tb=short --strict-markers --cov-report=term-missing --cov-report=html --cov=.'

testpaths = ['tests']

markers = [
    'serviceread: Тест сервиса чтения',
    'servicereg: Тест сервиса регистрации',
    'get: Тест get эндпоинтов',
    'post: Тест post эндпоинтов'
]

filterwarnings = [
    "ignore::DeprecationWarning:passlib.*",
    "ignore::DeprecationWarning:crypt.*",
]